export default [
  {
    ignores: ["node_modules/**", "third_party/**", "web-ext-artifacts/**"],
  },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        browser: "readonly",
        clearTimeout: "readonly",
        document: "readonly",
        getComputedStyle: "readonly",
        globalThis: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        importScripts: "readonly",
        InputEvent: "readonly",
        JSDOMParser: "readonly",
        KeyboardEvent: "readonly",
        location: "readonly",
        FirefoxReaderService: "readonly",
        PageContextDirective: "readonly",
        PageContextMessages: "readonly",
        PageContextPrompt: "readonly",
        PageContextProviders: "readonly",
        PageContextText: "readonly",
        performance: "readonly",
        Readability: "readonly",
        requestAnimationFrame: "readonly",
        self: "readonly",
        setTimeout: "readonly",
        URL: "readonly",
        Worker: "readonly",
        XMLSerializer: "readonly",
      },
    },
    rules: {
      "no-constant-condition": "error",
      "no-console": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-redeclare": "error",
      "no-shadow": "error",
      "no-throw-literal": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-var": "error",
      "object-shorthand": "error",
      "prefer-const": "error",
      radix: "error",
    },
  },
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "commonjs",
      globals: {
        __dirname: "readonly",
        console: "readonly",
        document: "readonly",
        getComputedStyle: "readonly",
        process: "readonly",
        require: "readonly",
        clearTimeout: "readonly",
        setTimeout: "readonly",
        URL: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "no-constant-condition": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-redeclare": "error",
      "no-shadow": "error",
      "no-throw-literal": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "no-unused-vars": "error",
      "no-var": "error",
      "object-shorthand": "error",
      "prefer-const": "error",
      radix: "error",
    },
  },
];
